seq: mandelbrot_seq.c
	gcc -o mandelbrot_seq mandelbrot_seq.c
	./mandelbrot_seq -2.5 1.5 -2.0 2.0 11500

pth: mandelbrot_pth.c
	gcc -pthread -o mandelbrot_pth mandelbrot_pth.c
	./mandelbrot_pth -2.5 1.5 -2.0 2.0 11500


